### PR TITLE
Error Pages

### PR DESCRIPTION
**Pull request by PavlushaAnd**
implemented 400, 401, 403, 500 pages; added password validation for registration form;

### CODE REVIEW

**Comment by llanos1205** [comment]
Requires implementation of error 404 when the users types an non-existent url

**Review by llanos1205 — CHANGES_REQUESTED** [review]
Need 404 implementation in non existent urls

**Review by ShunMura99 — APPROVED** [review]

**Review by ShunMura99 — APPROVED** [review]

**Comment by PavlushaAnd** [comment]
Updated!

**Review by llanos1205 — CHANGES_REQUESTED** [review]
almost perfect,
Although this changes in the lists shows the correct partial view for 404, it only happens when there is nothing on the catalog on the first call, 
This should also be rendered on search (you migth need to change the JS script in SOFT703A2.WebApp/Views/MarketPlace/Index.cshtml) and in all the 3 search engines

**Review by llanos1205 — APPROVED** [review]

**Pull request merged**
